app = "segfault-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  SEGFAULT_DB_PATH = "/data/segfault.db"
  SEGFAULT_ENABLE_TICK_LOOP = "1"
  SEGFAULT_REPLAY_LOGGING = "1"
  SEGFAULT_REPLAY_COMPRESS = "0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[mounts]]
  source = "segfault_data"
  destination = "/data"
